close all   %callback »Øµ÷º¯Êý
h = uicontrol('Style', 'pushbutton', 'String', 'Picture',...
    'Position', [20 150 100 70], 'Callback', 'load flujet;image(X)')
hpop = uicontrol('Style', 'popup',...
       'String', 'hsv|hot|cool|gray',...
       'Position', [20 320 100 50],...
       'Callback', 'setmap');